### ISSUE TITLE
Reading bibly.json

### ISSUE THREAD

**Issue by menesro** [michael-emmi/bibly#10]
I have an issue that seems to be related to reading bibly.json. Running bibly 1.1.5, I get "warning: could not read bibly.json".

I'm running it on macOS 10.15.7, and using the version 14.15.1 of node.js. Here is the bibly.json (identical to the one in the readme, modulo the name of the latex file)

{
  "latex": "main.tex",
  "databases": {
    "DBLP": {
      "url": "https://dblp.uni-trier.de/rec",
      "suffix": ".bib",
      "parameters": {
        "param": 1
      },
    }
  }
}

**Comment by michael-emmi** [comment]
First of all this is invalid JSON (due to trailing comma). Second, the `databases` object should have a `file` property. I’ve updated the README and added validation code in 1a64b3f.
