### ISSUE TITLE
Issue with running bibly command

### ISSUE THREAD

**Issue by nelaturuk** [michael-emmi/bibly#11]
Hi I am not able to run the bibly command after the npm installation. I have tried the command both in windows and ubuntu wsl. Any idea why it is causing the issue. I have used this library before and I dint see this kind of error. I do have the json file in the repo as mentioned in readme. 

![image](https://user-images.githubusercontent.com/3939682/137533591-43cd87a2-3064-483d-afe2-b1278e184812.png)

**Comment by michael-emmi** [comment]
Seems like your version of NodeJS does not support Optional Chaining and thus must be earlier than version 14: https://cri.dev/posts/2020-05-01-Optional-chaining-in-Node.js-14/

Perhaps upgrading to NodeJS 14+ will help.
